#!/usr/bin/bash

#waybar &

swaync
notify-send -a aurora "hello $(whoami)"

# Clipboard Management
exec-once = wl-paste --watch cliphist store
wl-clip-persist --clipboard regular --all-mime-type-regex '(?i)^(?!image/x-inkscape-svg).+'

# Applets
blueman-applet &
nm-applet --indicator &\

# WL
exec-once=swww init
exec-once=swww img ~/.config/hypr/wallpaper.jpg

# Fixes
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all & # Apps opening up long fix
exec-once = rofi -enable-drw-true # Better rofi integration in Wayland
