#!/usr/bin/bash

waybar &

swaync
notify-send -a aurora "hello $(whoami)"

# Clipboard Management
exec-once = wl-paste --watch cliphist store
wl-clip-persist --clipboard regular --all-mime-type-regex '(?i)^(?!image/x-inkscape-svg).+'

# Applets
blueman-applet &
nm-applet --indicator &\

# Wallpaper
hyprpaper &
exec-once = ~/.scripts/wpch.sh

# Fixes
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland --all & # Apps opening up long fix, works only on SystemD
##You can just do this instead;
#export WAYLAND_DISPLAY=wayland-1
#export XDG_CURRENT_DESKTOP=Hyprland

exec-once = rofi -enable-drw-true # Better rofi integration in Wayland
